import type { CandidateProfile, MatchResult, UserProfile } from './types';

export const MOCK_CANDIDATES: CandidateProfile[] = [
  {
    id: 'c1',
    name: 'Maya Chen',
    course: 'ECON 101',
    seatZone: 'back-right',
    commStyle: 'text-first',
    mbti: 'INFJ',
    hometown: 'Eau Claire, WI',
    languages: ['English', 'Mandarin'],
    zodiac: 'Virgo',
    resumeText: 'Econ major, sustainability club, data viz intern at a local nonprofit.',
    antiResume: {
      struggle: 'Public speaking in large lectures',
      failure: 'Dropped an organic chem class twice',
      curiosity: 'How rural Wisconsin towns adapt to climate policy',
    },
    sharedLectures: 14,
  },
  {
    id: 'c2',
    name: 'Jordan Okafor',
    course: 'ECON 101',
    seatZone: 'back-left',
    commStyle: 'meet-first',
    mbti: 'ENTP',
    hometown: 'Milwaukee, WI',
    languages: ['English', 'Igbo'],
    zodiac: 'Leo',
    resumeText: 'Political science major, debate team, canvassed for local elections.',
    antiResume: {
      struggle: 'Sitting still through long lectures',
      failure: 'Lost a debate final in high school I thought I had won',
      curiosity: 'Why people who disagree politically still end up friends',
    },
    sharedLectures: 9,
  },
  {
    id: 'c3',
    name: 'Riley Nakamura',
    course: 'ECON 101',
    seatZone: 'middle-right',
    commStyle: 'text-first',
    mbti: 'INTP',
    hometown: 'Madison, WI',
    languages: ['English', 'Japanese'],
    zodiac: 'Pisces',
    resumeText: 'CS + econ double major, built a bus-arrival predictor for campus.',
    antiResume: {
      struggle: 'Starting conversations with strangers',
      failure: 'A side project that got 3 users and crashed',
      curiosity: 'Whether small-town economics really works differently',
    },
    sharedLectures: 11,
  },
  {
    id: 'c4',
    name: 'Sam Rodriguez',
    course: 'ECON 101',
    seatZone: 'front-center',
    commStyle: 'meet-first',
    mbti: 'ESFJ',
    hometown: 'Green Bay, WI',
    languages: ['English', 'Spanish'],
    zodiac: 'Aries',
    resumeText: 'Business major, student government treasurer, organized campus food drives.',
    antiResume: {
      struggle: 'Asking for help when I need it',
      failure: 'Planned an event that only 5 people showed up to',
      curiosity: 'Why some communities trust institutions and others do not',
    },
    sharedLectures: 16,
  },
  {
    id: 'c5',
    name: 'Priya Patel',
    course: 'ECON 101',
    seatZone: 'middle-left',
    commStyle: 'text-first',
    mbti: 'ISFJ',
    hometown: 'Appleton, WI',
    languages: ['English', 'Gujarati', 'Hindi'],
    zodiac: 'Cancer',
    resumeText: 'Pre-med, volunteers at free clinic, tutors high school chemistry.',
    antiResume: {
      struggle: 'Saying no to commitments',
      failure: 'Burned out sophomore year trying to do everything',
      curiosity: 'How immigrant families navigate healthcare systems',
    },
    sharedLectures: 7,
  },
  {
    id: 'c6',
    name: 'Alex Kim',
    course: 'ECON 101',
    seatZone: 'back-center',
    commStyle: 'meet-first',
    mbti: 'ESTP',
    hometown: 'La Crosse, WI',
    languages: ['English', 'Korean'],
    zodiac: 'Sagittarius',
    resumeText: 'Marketing major, runs a small Etsy shop, plays intramural soccer.',
    antiResume: {
      struggle: 'Finishing things I start',
      failure: 'Three abandoned business ideas in two years',
      curiosity: 'What makes people buy things they do not really need',
    },
    sharedLectures: 12,
  },
  {
    id: 'c7',
    name: 'Taylor Washington',
    course: 'ECON 101',
    seatZone: 'front-left',
    commStyle: 'text-first',
    mbti: 'INFP',
    hometown: 'Racine, WI',
    languages: ['English'],
    zodiac: 'Aquarius',
    resumeText: 'English major, writes for campus literary magazine, barista at local cafe.',
    antiResume: {
      struggle: 'Making decisions under pressure',
      failure: 'Switched majors three times before landing on English',
      curiosity: 'Why people stay in dying towns instead of leaving',
    },
    sharedLectures: 8,
  },
  {
    id: 'c8',
    name: 'Dev Sharma',
    course: 'ECON 101',
    seatZone: 'middle-center',
    commStyle: 'meet-first',
    mbti: 'ENTJ',
    hometown: 'Kenosha, WI',
    languages: ['English', 'Punjabi'],
    zodiac: 'Capricorn',
    resumeText: 'Engineering major, hackathon regular, building a campus ride-share app.',
    antiResume: {
      struggle: 'Listening without trying to solve',
      failure: 'Lost my entire team on a group project because I was too controlling',
      curiosity: 'How people decide what problems are worth solving',
    },
    sharedLectures: 13,
  },
  {
    id: 'c9',
    name: 'Emma Larson',
    course: 'ECON 101',
    seatZone: 'front-right',
    commStyle: 'text-first',
    mbti: 'ISTJ',
    hometown: 'Oshkosh, WI',
    languages: ['English', 'Swedish'],
    zodiac: 'Taurus',
    resumeText: 'Accounting major, treasurer of two clubs, meticulous planner.',
    antiResume: {
      struggle: 'Being spontaneous',
      failure: 'Missed out on a study abroad because I overthought the logistics',
      curiosity: 'Why some people are okay with uncertainty',
    },
    sharedLectures: 15,
  },
  {
    id: 'c10',
    name: 'Marcus Johnson',
    course: 'ECON 101',
    seatZone: 'back-right',
    commStyle: 'meet-first',
    mbti: 'ENFP',
    hometown: 'Wausau, WI',
    languages: ['English'],
    zodiac: 'Gemini',
    resumeText: 'Sociology major, campus radio DJ, organizes open mic nights.',
    antiResume: {
      struggle: 'Following through on long-term goals',
      failure: 'Started a podcast that died after episode 4',
      curiosity: 'What makes a random group of people become a real community',
    },
    sharedLectures: 10,
  },
  {
    id: 'c11',
    name: 'Aisha Anderson',
    course: 'CS 200',
    seatZone: 'back-left',
    commStyle: 'text-first',
    mbti: 'INTJ',
    hometown: 'Madison, WI',
    languages: ['English', 'Arabic'],
    zodiac: 'Scorpio',
    resumeText: 'CS major, hackathon participant, building mobile apps.',
    antiResume: {
      struggle: 'Asking questions in class',
      failure: 'Failed a class I thought I would ace',
      curiosity: 'Why some friendships last and others fade',
    },
    sharedLectures: 5,
  },
  {
    id: 'c12',
    name: 'Ben Brown',
    course: 'CS 300',
    seatZone: 'front-center',
    commStyle: 'meet-first',
    mbti: 'ENTP',
    hometown: 'Milwaukee, WI',
    languages: ['English'],
    zodiac: 'Gemini',
    resumeText: 'CS major, teaching assistant, loves algorithms.',
    antiResume: {
      struggle: 'Time management',
      failure: 'Lost a leadership position due to poor communication',
      curiosity: 'How people find meaning in routine work',
    },
    sharedLectures: 12,
  },
  {
    id: 'c13',
    name: 'Carlos Chang',
    course: 'CS 400',
    seatZone: 'middle-right',
    commStyle: 'text-first',
    mbti: 'ISTP',
    hometown: 'Green Bay, WI',
    languages: ['English', 'Spanish'],
    zodiac: 'Taurus',
    resumeText: 'CS major, open source contributor, interested in systems.',
    antiResume: {
      struggle: 'Perfectionism',
      failure: 'Quit a team sport after one season',
      curiosity: 'What makes a place feel like home',
    },
    sharedLectures: 8,
  },
  {
    id: 'c14',
    name: 'Diana Davis',
    course: 'CS 537',
    seatZone: 'back-right',
    commStyle: 'meet-first',
    mbti: 'ENFJ',
    hometown: 'Kenosha, WI',
    languages: ['English', 'French'],
    zodiac: 'Leo',
    resumeText: 'CS major, research assistant, studying operating systems.',
    antiResume: {
      struggle: 'Imposter syndrome',
      failure: 'Abandoned a passion project halfway through',
      curiosity: 'Why we remember certain moments and forget others',
    },
    sharedLectures: 14,
  },
  {
    id: 'c15',
    name: 'Ethan Evans',
    course: 'ECE 354',
    seatZone: 'middle-left',
    commStyle: 'text-first',
    mbti: 'INTP',
    hometown: 'Racine, WI',
    languages: ['English'],
    zodiac: 'Aquarius',
    resumeText: 'ECE major, robotics club, building embedded systems.',
    antiResume: {
      struggle: 'Procrastination',
      failure: 'Missed an important deadline',
      curiosity: 'How strangers become friends',
    },
    sharedLectures: 6,
  },
  {
    id: 'c16',
    name: 'Fatima Fischer',
    course: 'CS 200',
    seatZone: 'front-left',
    commStyle: 'meet-first',
    mbti: 'ESFJ',
    hometown: 'Appleton, WI',
    languages: ['English', 'Arabic'],
    zodiac: 'Cancer',
    resumeText: 'CS major, peer mentor, passionate about education.',
    antiResume: {
      struggle: 'Setting boundaries',
      failure: 'Burned a bridge with a mentor',
      curiosity: 'What drives people to take big risks',
    },
    sharedLectures: 11,
  },
  {
    id: 'c17',
    name: 'Grace Garcia',
    course: 'CS 300',
    seatZone: 'back-center',
    commStyle: 'text-first',
    mbti: 'ISFP',
    hometown: 'Waukesha, WI',
    languages: ['English', 'Spanish'],
    zodiac: 'Pisces',
    resumeText: 'CS major, UI/UX designer, loves creative coding.',
    antiResume: {
      struggle: 'Public speaking',
      failure: 'Got rejected from my dream internship',
      curiosity: 'Why some communities thrive and others struggle',
    },
    sharedLectures: 9,
  },
  {
    id: 'c18',
    name: 'Hassan Harris',
    course: 'CS 400',
    seatZone: 'middle-center',
    commStyle: 'meet-first',
    mbti: 'ESTJ',
    hometown: 'Oshkosh, WI',
    languages: ['English', 'Arabic'],
    zodiac: 'Aries',
    resumeText: 'CS major, startup founder, building fintech solutions.',
    antiResume: {
      struggle: 'Accepting criticism',
      failure: 'Started a club that fell apart',
      curiosity: 'How people change their minds about deeply held beliefs',
    },
    sharedLectures: 13,
  },
  {
    id: 'c19',
    name: 'Iris Ibrahim',
    course: 'CS 537',
    seatZone: 'front-right',
    commStyle: 'text-first',
    mbti: 'INFP',
    hometown: 'Eau Claire, WI',
    languages: ['English', 'Arabic'],
    zodiac: 'Libra',
    resumeText: 'CS major, interested in AI ethics and fairness.',
    antiResume: {
      struggle: 'Working in groups',
      failure: 'Bombed a presentation I prepared for weeks',
      curiosity: 'What makes art resonate with people',
    },
    sharedLectures: 7,
  },
  {
    id: 'c20',
    name: 'Jake Jones',
    course: 'ECE 354',
    seatZone: 'back-left',
    commStyle: 'meet-first',
    mbti: 'ESTP',
    hometown: 'Janesville, WI',
    languages: ['English'],
    zodiac: 'Sagittarius',
    resumeText: 'ECE major, hardware hacker, loves circuit design.',
    antiResume: {
      struggle: 'Staying focused',
      failure: 'Lost touch with my best friend from high school',
      curiosity: 'Why certain songs make us cry',
    },
    sharedLectures: 10,
  },
];

export function mockMatch(user: UserProfile, mode: 'similarity' | 'bridge'): MatchResult {
  const introvert = Boolean(user.introvertMode);

  const fullPicks = mode === 'bridge'
    ? [MOCK_CANDIDATES[1], MOCK_CANDIDATES[0], MOCK_CANDIDATES[2]]
    : [MOCK_CANDIDATES[0], MOCK_CANDIDATES[2], MOCK_CANDIDATES[1]];

  const picks = introvert ? fullPicks.slice(0, 2) : fullPicks;

  const sharedGround = introvert
    ? (mode === 'bridge'
        ? `Two people from different corners of ${user.course}. Each of you wrote something curious on your anti-resume about understanding people who think differently. Small overlap, real one.`
        : `You two have been sitting within twenty feet of each other for weeks. Both of you prefer quieter entry points. Both anti-resumes mention curiosity about how communities actually work.`)
    : (mode === 'bridge'
        ? `You three come from different corners of ${user.course} and different corners of Wisconsin. But each of you wrote something on your anti-resume about wanting to understand people who do not think the way you do. That is the thread.`
        : `You three have been sitting within twenty feet of each other for most of the semester. You all lean toward quieter entry points to conversation, and all three anti-resumes mention curiosity about how communities actually work.`);

  const isText = user.commStyle === 'text-first';

  let introMessage: string;
  if (introvert) {
    introMessage = `Hi — a quiet intro from Ripple, no rush on any of this.\n\nThe two of you have been sharing a room in ${user.course} all semester (one of you has been there fourteen times). You each wrote something honest on your anti-resume about a curiosity that does not come up in normal small talk.\n\nWhenever you want, consider trading one line on that curiosity. Reply in a day, reply in a week, or do not. No pressure either way.`;
  } else if (isText) {
    introMessage = `Hey — this is a soft intro from Ripple. The three of you have overlapped in ${user.course} more than you probably realized (one of you has shared the room 14 times this semester). No pressure to meet up yet. If you're up for it, trade one line on your anti-resume "curiosity" and see where it goes.`;
  } else {
    introMessage = `Hi all — Ripple here. You've been sharing the back half of ${user.course} all semester. Since you all said you prefer meeting in person, try this: same row, 10 minutes after Thursday's lecture, grab coffee at the union. Bring the one thing from your anti-resume you'd actually talk about out loud.`;
  }

  const bridgeScore = mode === 'bridge' ? 78 : 42;
  const depthScore = introvert ? (mode === 'bridge' ? 74 : 82) : undefined;

  return {
    candidates: picks,
    sharedGround,
    introMessage,
    bridgeScore,
    depthScore,
  };
}
